### ISSUE TITLE
Export all nodes - not just the first.

### ISSUE THREAD

**Issue by IngwiePhoenix** [chemzqm/dom#3]
As ween here:

https://github.com/chemzqm/dom/blob/master/lib/index.js#L9

The actual array of nodes is not supported. `this.el` is a single node at all times. If used with a query engine such as [qwery](http://npmjs.org/qwery), there is no way of actually accessing the collected nodes.

**Comment by chemzqm** [comment]
Yes it's designed to be a single node all times,  would that solve your problem if I add a reference like `this.els` which reference to the array of nodes you have pass in?

**Comment by IngwiePhoenix** [comment]
Yep, that would definitively help :)

**Comment by chemzqm** [comment]
Fixed
